@WebApiDemo_HostAddress = http://localhost:5255

GET {{WebApiDemo_HostAddress}}/shirts/

###
GET {{WebApiDemo_HostAddress}}/shirt/1


###
DELETE {{WebApiDemo_HostAddress}}/delete/1

###
PUT {{WebApiDemo_HostAddress}}/update/21